//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scenes/Scene2_CherryBomb/Input System/ClawControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ClawControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ClawControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ClawControls"",
    ""maps"": [
        {
            ""name"": ""Claw"",
            ""id"": ""0190f307-4679-4818-b5dc-e6ad8e8faf19"",
            ""actions"": [
                {
                    ""name"": ""MoveClaw"",
                    ""type"": ""Button"",
                    ""id"": ""e2d7b2a9-660c-4868-a50c-b0822adceed5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b3fa7b78-6509-49a9-8cd0-c8094ac7d575"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveClaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Claw
        m_Claw = asset.FindActionMap("Claw", throwIfNotFound: true);
        m_Claw_MoveClaw = m_Claw.FindAction("MoveClaw", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Claw
    private readonly InputActionMap m_Claw;
    private IClawActions m_ClawActionsCallbackInterface;
    private readonly InputAction m_Claw_MoveClaw;
    public struct ClawActions
    {
        private @ClawControls m_Wrapper;
        public ClawActions(@ClawControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveClaw => m_Wrapper.m_Claw_MoveClaw;
        public InputActionMap Get() { return m_Wrapper.m_Claw; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ClawActions set) { return set.Get(); }
        public void SetCallbacks(IClawActions instance)
        {
            if (m_Wrapper.m_ClawActionsCallbackInterface != null)
            {
                @MoveClaw.started -= m_Wrapper.m_ClawActionsCallbackInterface.OnMoveClaw;
                @MoveClaw.performed -= m_Wrapper.m_ClawActionsCallbackInterface.OnMoveClaw;
                @MoveClaw.canceled -= m_Wrapper.m_ClawActionsCallbackInterface.OnMoveClaw;
            }
            m_Wrapper.m_ClawActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MoveClaw.started += instance.OnMoveClaw;
                @MoveClaw.performed += instance.OnMoveClaw;
                @MoveClaw.canceled += instance.OnMoveClaw;
            }
        }
    }
    public ClawActions @Claw => new ClawActions(this);
    public interface IClawActions
    {
        void OnMoveClaw(InputAction.CallbackContext context);
    }
}
